### ISSUE TITLE
basic stopped working key P, L and others not working

### ISSUE THREAD

**Issue by MacGyver4B** [visrealm/hbc-56#7]
I think this is broken since last update.
Typing print is not possible.
Gives error bell.

**Comment by visrealm** [comment]
Thanks. I have seen this one too. Just haven't had the time to look into it yet.

**Comment by MacGyver4B** [comment]
You are insane! You solve and close issues faster than I can file them.
Great work!
I would understand that one you changed it from two separate key board handling functions Ctrl+C and the rest to one that handles both right?
What I do not understand why only the right quarter of the keyboard was affected. Would you be so kind to explain that?

**Comment by visrealm** [comment]
No problem. It helps to have a decent debugger ;)

As for the keyboard issue. It comes down to modifying the X register where EhBASIC expects it to be left alone. In my input routine, the X register was set to the PS/2 scancode (since the change to my interrupt-driven keyboard controller). The scancodes on the right side of the keyboard have higher values.

If you look at the EhBASIC input routine:
 
![ehbasic_input](https://user-images.githubusercontent.com/6883112/160945411-99436a06-a5cb-48fd-9ee1-3eb125465ee4.PNG)

It compres the X register to `Ibuffe-Ibuffs` (which is $47 in my case). Looking at the [PS/2 scancodes](https://techdocs.altium.com/display/FPGA/PS2+Keyboard+Scan+Codes) we can see the characters affected were all greater than $47.
